# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  url: redis://redistogo:c566e1fd2625426200c17839794ff48c@hammerjaw.redistogo.com:10749/

development:
  adapter: async

test:
  adapter: async
